### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by os8rxn** [kumarsamir/resume#1]
![favicon](https://cloud.githubusercontent.com/assets/3690178/10599783/d02fea20-7737-11e5-8f66-2fa56a5c30e1.png)

**Comment by os8rxn** [comment]
Add the black and white instead.

![favicon_black](https://cloud.githubusercontent.com/assets/3690178/10600732/34a497d8-773f-11e5-8749-8bd62e0e7bcb.png)

**Comment by kumarsamir** [comment]
![favicon](https://cloud.githubusercontent.com/assets/3690178/10602696/74eddd38-774c-11e5-9f6f-358093435b0d.png)

**Comment by os8rxn** [comment]
![favicon](https://cloud.githubusercontent.com/assets/3690178/10607210/8e0c91a6-776a-11e5-8eed-7f47f6bb8840.png)
